# Generated by Django 5.2 on 2025-05-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesEngine', '0002_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(),
        ),
    ]
